name: 'Download artifact from a github workflow run'
description: 'Download an artifact from GitHub workflow (aka. build) for a specific run id'
author: 'Benjamin Day Consulting, Inc.'
inputs:
  token:
    required: true
    description: 'token for accessing github api'
    default: ''
  repository_owner:
    required: true
    description: 'github account owner'
    default: ''
  repository_name:
    required: true
    description: 'name of the git repository that has the artifact to download'
    default: ''
  workflow_name:
    required: true
    description: 'name of the workflow (aka. build) that created the artifact'
    default: ''
  artifact_name:
    required: true
    description: 'name of the artifact to download'
    default: ''
  run_id:
    required: true
    description: 'the run id value that you want to download the artifact from'
    default: ''
  download_path:
    required: true
    description: 'path on the agent to download the artifact zip to'
    default: ''
  download_filename:
    required: true
    description: 'filename for the downloaded artifact zip (suggestion: this should end with the .zip extension)'
    default: ''

runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'hard-drive'
  color: 'blue'
